version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: localfast_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localfast_db
    ports: ["5434:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
